# Generated by Django 5.1.5 on 2025-06-06 05:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to=accounts.models.user_profile_path),
        ),
    ]
